### ISSUE TITLE
SASS Colours

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-react-toolkit#1]
Would be nice to have these served up as SASS variables so we all match :)

**Comment by benlancaster** [comment]
Some worthwhile reading on the subject here: http://davidwalsh.name/sass-color-variables-dont-suck

**Comment by rmallols** [comment]
Really interesting Ben, thanks for sharing :).

**Comment by alexjfno1** [comment]
Should this issue move to the [nowtv-toolkit](https://github.com/sky-uk/nowtv-toolkit) as the react toolkit styles will eventually disappear as they are replaced by the base toolkit ones.

**Comment by peter-mouland** [comment]
agreed with @alexjfno1 :+1:

**Comment by alexjfno1** [comment]
On second thoughts if you want the colour variables and are using the react-toolkit you will also have to import the base toolkit. Would it be better to just expose the colours from the base toolkit through the react-toolkit?

**Comment by NowTV-Assurance** [comment]
This will now come from the style guide now.
