### ISSUE TITLE
NowTV font not being used on the docs

### ISSUE THREAD

**Issue by rogerfranklin2** [sky-uk/nowtv-react-toolkit#104]
Not sure when this was broken but it looks like the docs are not using the NowTV font, anyone else notice when these broke?

## Current behavior/Screenshot:

 - http://nowtv-react-toolkit.herokuapp.com/

## Steps to reproduce:

 1. Go to link
 2. Look at fonts

**Comment by nowarkdev** [comment]
I think the docs need to import the fonts.scss file from the styleguide. I think it was split out in a pull request a while ago.

@roryp2
