### ISSUE TITLE
Make whole FAQ clickable

### ISSUE THREAD

**Issue by rogerfranklin2** [sky-uk/nowtv-react-toolkit#110]
Short description of the issue

## Current behavior/Screenshot:

 - Currently you cannot click on the chevron to open and close the chevron you have to click on the text. 

## Expected behavior/Screenshot:

 - To be able to open/close FAQ by using chevron

Adding so its not forgotten, not sure if this should be done as part of the rewrite or now?

**Comment by bentidy** [comment]
:+1:
