### ISSUE TITLE
What is stable?

### ISSUE THREAD

**Issue by andrewmerrell** [sky-uk/nowtv-react-toolkit#124]
Suggestions of criteria for what we class as a stable project ready for bumping to version 1 of the toolkit

**Comment by tomatau** [comment]
Generally stability means an API won't change much, but I don't think you can ever prove that unless you have a crystal ball... so.

For me, stability is mostly about trusting that the components won't break whilst they continue to get maintained and built on. A complete functional testing suite is most important there.

Next, it should offer good support for consumers... so documentation is important there to set expectations.

After that stability is probably about meeting it's initial goals, so maybe:
- being a shared codebase
- being accessible
- being extendible / composable
- being consistent... so things like linting rules, contibuting guidelines, testing practices, and these sorts of checks really help with that.

**Comment by peter-mouland** [comment]
To add to the functional testing mentioned above, this should include :
 * a guarantee that components work cross-browser and for keyboard and screen-reader users.

**Comment by ariley90** [comment]
For me this means:
- Components work in all supported browsers
- Components are agnostic to where they are used (e.g the top level element should fill the space where)
- accessible
- Test coverage for behaviour / visual regression for styles
- Agreement from contributors on the implementation/design.
- Documentation on how to use the component & any design decisions that may seem strange to a new user.
- Rate of change with regards to designs is at an acceptable level. This is in relation to some core components such as Typography. We have seen these then change the implementation of components that build upon them.

**Comment by bdo** [comment]
For me this means:
- no known significant bugs
- being consumable from npm
- being used by more than one team
- examples in the shape of docs / unit tests so that I can know how to use each component
- no breaking changes are required for components to be usable

**Comment by peter-mouland** [comment]
A lot of changes have happened since the start of the project , so it makes sense to have a review of existing components.  I know there are some that would benefit from changes and i don't know if we could call it stable without this review.

This would obviously be last on the list of things to do before we are 'stable'.

**Comment by peter-mouland** [comment]
discussion is ongoing in toolkit meetings
