### ISSUE TITLE
`dist` should be ignored from git

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#20]

**Comment by bentidy** [comment]
@rogerfranklin2 I most teams are importing the styles from the dist and pulling the toolkit from github, so this needs more discussion.

Why do you want to ignore it?

**Comment by peter-mouland** [comment]
I think dist should be what is pushed to CDN.

Teams should then pull from the source only the flie they would like.  If they are pulling in from dist , this means they are adding over 700kb to their bundle where as they may only need to button which would be less than 1k.

Dist in github also pollutes PR's.  Ie. it is hard to see the raw code changes when every files within dist updates with every PR.

**Comment by alexjfno1** [comment]
If your using scss or sass it shouldn't matter if you get it from the dist or the original src file should it?

**Comment by peter-mouland** [comment]
The size differences i mentioned above are to do with the compiled JS (which the react toolkit currently includes the whole of React and other functions to transform es6 to es5).  We have done a test within the assurance app to see the difference it makes!

**Comment by alexjfno1** [comment]
Oh yeah sorry, slightly misread that. Seeing as all the teams using the toolkit are using webpack or some sort of tool to transform es6 to es5 the toolkit could be just raw es6 files and then the project importing it is responsible for doing that transformation.

**Comment by bentidy** [comment]
@rogerfranklin2 

We looked at building a module in pure es6 but ran into difficulties and not sure if it is possible. Might have been something around the import/export but can't be sure

**Comment by peter-mouland** [comment]
@rogerfranklin2
pure es6, i.e. without react?
We've done the react button and integrated it directly in our app.  We updated the Readme to try and describe the process. maybe come over to see how we did it if the readme isn't working for you

**Comment by rogerfranklin2** [comment]
Not the individual components but the module it's self. But happy for someone else to give it a go to see if it works. The reason from the node team was that the spec for modules isn't finalised yet

**Comment by peter-mouland** [comment]
this is going off-topic. feel free to raise another issue or come over for a chat

**Comment by NowTV-Assurance** [comment]
Agreed to remove dist from git but ensure it remains on npm. No CDN support for now.
