### ISSUE TITLE
Depend on the nowtv-toolkit (buttons + colours)

### ISSUE THREAD

**Issue by andrewmerrell** [sky-uk/nowtv-react-toolkit#21]
As per last global meetup start moving styles to the generic toolkit, an initial commit should consider removing the colours and depending on the base button styles.

 - [x] update button styles
 - [x] remove colours from react toolkit

**Comment by rogerfranklin2** [comment]
Is this now done with #28?

If not maybe we should make more specific issues so we know what needs to be done

**Comment by peter-mouland** [comment]
#25 and #28 were mean the buttons are done. I'll update the title and and a list to this issue to be more specific

**Comment by peter-mouland** [comment]
#48 fixes this
