### ISSUE TITLE
use React 0.14 from a NowTV CDN

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#29]
do not include react in the bundle (i.e. /dist files)

 - [x] push js to `/static` (i.e. not versioned directory)
 - [x] Pushing the js to a CDN should be done via a script which gets run manually (as it wont happen often).
 - [x] Update ReadMe to inform projects to use the CDN

**Comment by rogerfranklin2** [comment]
Yep sounds good. Has the react cdn been done yet?

**Comment by peter-mouland** [comment]
not yet - I was talking to Jacob about how shop push files to akamai and that sounded like a good route.
feel free to label this as in progress if you want to pick it up!

**Comment by andrewmerrell** [comment]
Google and cdnjs have the following format
`/ajax/libs/<library-name>/<version>`

Suggest we drop the ajax portion...
`/libs/<library-name>/<version> `

**Comment by bdo** [comment]
OK, @rogerfranklin2 and I have started with the following:
- [libs/react/0.14.6/react.js](http://web.static.nowtv.com/libs/react/0.14.6/react.js)
- [libs/react/0.14.6/react.min.js](http://web.static.nowtv.com/libs/react/0.14.6/react.min.js)
- [libs/react/0.14.6/react-dom.js](http://web.static.nowtv.com/libs/react/0.14.6/react-dom.js)
- [libs/react/0.14.6/react-dom.min.js](http://web.static.nowtv.com/libs/react/0.14.6/react-dom.min.js)

Please add the ones you will be using

**Comment by nowarkdev** [comment]
@acnalesso: Any progress in this? Can we start using it?

Thanks

**Comment by peter-mouland** [comment]
I reckon the README.md needs updating, but the files look good to go

**Comment by peter-mouland** [comment]
How do other push to CDN, is there a build script we can run to update these easily?

Also,  I've notices `react-dom.min.js` is only 1kb.  Should we not create a `react.bundle.js` instead which includes both these files?
