### ISSUE TITLE
Remove Modals

### ISSUE THREAD

**Issue by alexjfno1** [sky-uk/nowtv-react-toolkit#30]
No team is using or plan to use the modal so it should be removed for the time being.

**Comment by bentidy** [comment]
![image](https://cloud.githubusercontent.com/assets/778755/12229630/9891b97c-b841-11e5-9508-982ea7e6f3dd.png)

**Comment by peter-mouland** [comment]
:+1:

**Comment by alexjfno1** [comment]
DONE!
