### ISSUE TITLE
Transpile components to ES5

### ISSUE THREAD

**Issue by johnsibly** [sky-uk/nowtv-react-toolkit#34]
It is possible to add a build hook and transpile the source code to ES5. With this it would be possible to include only those components in a project that are used and not the full toolkit.js. @frikille

**Comment by peter-mouland** [comment]
the distributable code (ie. with /dist) is es5.

ideally the js components themselves should be written within `nowtv-toolkit` (which would be es5).  These raw components have a proper api and emit events etc that react could hook into.
The react-toolkit would then consume them and wrap them ready for react.

this guy has it down : https://ponyfoo.com/articles/why-i-write-plain-javascript-modules

**Comment by bdo** [comment]
Closing this issue as properly answered by @peter-mouland
