### ISSUE TITLE
How to handle tracking?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#36]
this has come about from the discussion in this PR https://github.com/sky-uk/nowtv-react-toolkit/pull/33

Two schools of thought:

 * include `data-tracking-*` in the react components
    * this would bind the react-toolkit to a version of sky-tags
    * this would mean less code in the consuming projects

* emit events within the component which can then be hooked into to be tracked
    * this would separate concerns between unrelated projects
    * it would give more flexibility for each consuming i.e. via an common api

**Comment by bdo** [comment]
I'm in favour of data-tracking-* as it's simpler and does not currently tie us into a particular version of sky-tags. Only if sky-tags is changed to use something else will this be relevant.

Emitting events sounds overcomplicated for what we're trying to accomplish there.

**Comment by nowarkdev** [comment]
@bdo :+1:
