### ISSUE TITLE
Change tests to use enzyme

### ISSUE THREAD

**Issue by rogerfranklin2** [sky-uk/nowtv-react-toolkit#42]
Was wondering if there would be any complaints if we moved to something like enzyme for the tests. It provides us some helpers and a nicer testing API. The changes shouldn't take more than an hour to change. Would also be an opportunity to add test coverage and review the tests which we have.

I've [created a gist](https://gist.github.com/rogerfranklin2/0d93f229cfde9bbeaeeb) to have a look at the differences.

Thoughts?

**Comment by alexjfno1** [comment]
Looks alright to me.

**Comment by ldabiralai** [comment]
I think this would make sense seeing as we're starting to transition to enzyme across our other apps too.
