### ISSUE TITLE
Do we want to lint tests?

### ISSUE THREAD

**Issue by ldabiralai** [sky-uk/nowtv-react-toolkit#47]
Thoughts?

**Comment by peter-mouland** [comment]
none

**Comment by alexflorisca** [comment]
Don't really wana get into a massive debate about code style preferences as everyone's gona have an different opinion. But do have eshint setup up to run on pre-commit for assurance app. So we could just copy that across if people are happy with our setup:

https://github.com/sky-uk/nowtv-assurance/blob/master/.eslintrc

**Comment by alexjfno1** [comment]
Why not :+1: . We can just use the settings we have for the actual code can't we?

**Comment by peter-mouland** [comment]
still don't care :dancer:

**Comment by alexflorisca** [comment]
No one cares that you don't care :)

**Comment by peter-mouland** [comment]
#49 sorts this one out :)
