### ISSUE TITLE
Checkbox component is broken

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-react-toolkit#54]
Checkbox component is broken in the toolkit.

**Comment by peter-mouland** [comment]
who are you? how is it broken? do you have a screenshot of what is broken?

**Comment by nowarkdev** [comment]
It's not rendering at all in the styleguide docs. We are not using it in our apps and the reason we know it's broken is from our work on the styleguide. It needs more investigation to start with to see why it's broken.  

Anuj/Pierre
Web Sales

**Comment by nowarkdev** [comment]
@peter-mouland Hope it's enough information to atleast start a conversation. If you think it needs more details, please let us know.

Anuj/Pierre
Web Sales

**Comment by peter-mouland** [comment]
<img width="1117" alt="screen shot 2016-01-26 at 16 18 19" src="https://cloud.githubusercontent.com/assets/1727939/12586491/6f19d0da-c448-11e5-8324-eb93b89b64dc.png">

**Comment by nowarkdev** [comment]
Just adding username for reference:
Pierre -  @PLAGR34GTT 
Anuj - @andhapp

**Comment by rogerfranklin2** [comment]
I've found the issue its styles coming through from the style guide.
````css
.now-checkbox {
  position: absolute;
  left: -9999px;
}
```
means that its going off the screen but i'll fix this
