### ISSUE TITLE
heroku build failing

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#55]
<img width="359" alt="screen shot 2016-01-26 at 15 15 05" src="https://cloud.githubusercontent.com/assets/1727939/12584493/aba838d8-c43f-11e5-8d26-958bfeda52ad.png">
<img width="901" alt="screen shot 2016-01-26 at 15 15 16" src="https://cloud.githubusercontent.com/assets/1727939/12584494/accfd946-c43f-11e5-85f7-34842318f110.png">

**Comment by ldabiralai** [comment]
Closing as it was fixed in #58
