### ISSUE TITLE
Improve ESLint rules

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-react-toolkit#56]
At the moment, [ES lint rules](https://github.com/sky-uk/nowtv-react-toolkit/blob/master/.eslintrc) aren't comprehensive.

**Comment by rogerfranklin2** [comment]
Again like the other issue who is this, could you either post using your username or just write @yourusername so we know who it is raising these issues.

What rules do you want to add?

**Comment by nowarkdev** [comment]
Please have a look at the ESlint file that's linked to the initial issue. I am sure we can improve the rules to make it look similar to one of our apps. Thoughts?

Anuj/Pierre
Web Sales

**Comment by nowarkdev** [comment]
@rogerfranklin2 Forgot to tag you in. Have a look at response above.

**Comment by peter-mouland** [comment]
Anuj, do you have a github username we can link these issues to?

Sorry, i'm not sure what rules your apps have, could you be a bit more specific?

**Comment by nowarkdev** [comment]
@andhapp Here's my username. 

@peter-mouland We will update the rules to mirror our apps and open a PR for feedback. Sounds good?

**Comment by nowarkdev** [comment]
Just adding Pierre's username for reference @PLAGR34GTT

**Comment by peter-mouland** [comment]
@PLAGR34GTT have you noticed that this uses AirBnB linting is used in this project?  These are pretty thorough!

**Comment by peter-mouland** [comment]
will close this as i Assume no more comment means we are happy with AirBnB linting
