### ISSUE TITLE
.npmrc command making build fail

### ISSUE THREAD

**Issue by rogerfranklin2** [sky-uk/nowtv-react-toolkit#61]
Probably one for @peter-mouland 

What do we need to do to get this to run on circle properly?
https://circleci.com/gh/sky-uk/nowtv-react-toolkit/290

**Comment by peter-mouland** [comment]
hmm - it should be working...
we removed this line from circleci.yml because heroku also need the npmrc file
`  - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> ~/.npmrc`

so in theory, the change shouldn't have made a difference. The only thing i can see is that the PR is from your repo. would you weirdly have to add the environment variable NPM_TOKEN to your circleci settings too?

**Comment by rogerfranklin2** [comment]
I can show you this morning but it happens when I clone down sky-uk toolkit and try to npm install

**Comment by peter-mouland** [comment]
you will need an `NPM_TOKEN` environment variable locally or simply log into the NowTV private repo should be enough.  I should probably add something like this to the docs somewhere!

```
log into NowTV private repo using `npm login`
run `cat ~/.npmrc`
 Add `export NPM_TOKEN="AUTH-TOKEN-HERE"` to your ~/.bash_profile
```

**Comment by rogerfranklin2** [comment]
Yep its a setting in circleCI which is suppressing export of environment variables for fork PR builds. We can disable this if we want and allow the environment variables for forks.

As the token is NowTV key I suggest we either make it a public module then we won't need a token for circle( and its public on github anyway) or we allow it for forks which could have security concerns.

Thoughts?

**Comment by ldabiralai** [comment]
I think it should be a public npm module.

This will also make it easier to start using the react toolkit from the start, as you don't need to worry about npm details.

**Comment by peter-mouland** [comment]
Can you not add the key into your own circle setup?

**Comment by rogerfranklin2** [comment]
No, its not running on my circle its running on sky-uk.

If you look at the build you can see:
```
Suppressing export of environment variables DIVSHOT_TOKEN, NPM_TOKEN fork PR builds
```

So its a setting in the config for the project

**Comment by peter-mouland** [comment]
ah - ok, so if we allow the exporting of env vars, the PR can run - but i guess its not on automatically as people could use this setting to extract those env vars with a malicious code change within the PR.

Sounds like good practise would be not to check that box.

**Comment by rogerfranklin2** [comment]
I will ask the other guys their thoughts on making it public to fix this

**Comment by alexjfno1** [comment]
I think it makes sense to make this a public npm module seeing as the Styleguide is going public as well.

**Comment by ldabiralai** [comment]
The module is now public :+1:
