### ISSUE TITLE
investigate how to display code

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#79]
I'm not sure the current display of code is doing it for me.  Maybe we can use a service to help display them well, i.e. embed `gists` or `codePens`?

**Comment by rogerfranklin2** [comment]
Not for me, this will mean more code to maintain.

**Comment by tomatau** [comment]
We're already having to maintain the examples in the docs.  I agree that they're not so easy to follow (often crammed onto one line) and likely to go out of sync or just not document features.

Anyone have experience with JSDOC style tools that can generate a html book - to me that would be the best solution as the documentation for a component will be in the same file as a component. Also would encourage documenting propTypes directly.

**Comment by peter-mouland** [comment]
no experience here - but sounds like it might be good. Would be interesting to see a spike or something in a branch for a component if it doesn't take too long?

**Comment by alexjfno1** [comment]
Could we use something like https://github.com/reactjs/react-docgen

This way when someone adds a new component the docs are automatically generated.

**Comment by bdo** [comment]
The following looks promising as well:
https://github.com/sapegin/react-styleguidist

It does generate basic documentation and you can add examples using Markdown.

**Comment by peter-mouland** [comment]
seems to be going well with prs like https://github.com/sky-uk/nowtv-web-toolkit/pull/62
