### ISSUE TITLE
allow standard attrs to be passed to components

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#86]
we should be able to pass things like `data-` and `id` into each component without having to be specific each attr in the component code.

Spread works (`{...this.props}`) but this also add the other props that are used elsewhere.

**Comment by tomatau** [comment]
If you insert the spread first and extract the other props, the other attributes wont get overwritten, I think that would be a safer approach to persist the other props.

```js
const { childsProp, otherProp, ...props } = this.props;
<container-element {...props} className='important-required-thing' data-important {...etc} />
```

**Comment by alexjfno1** [comment]
Sounds good @tomatau

**Comment by bentidy** [comment]
:+1: @bdo

**Comment by peter-mouland** [comment]
this PR implements this: https://github.com/sky-uk/nowtv-react-toolkit/pull/90
be great to get some more reviews :)
