### ISSUE TITLE
Add NPM badge

### ISSUE THREAD

**Issue by alexjfno1** [sky-uk/nowtv-react-toolkit#92]
It would be nice to have an NPM badge with the latest version.

The package isn't public on NPM. I thought that we decided to make it public.

**Comment by ldabiralai** [comment]
:+1: 

Might be a good idea so people can see what version is on npm quickly.

**Comment by peter-mouland** [comment]
:+1:

**Comment by ldabiralai** [comment]
Closing now that this is merged
